### ISSUE TITLE
Page doesn't reload after making change in HTML file.

### ISSUE THREAD

**Issue by skrzepij** [Ihatetomatoes/webpack-101-hmr-css#1]
Hi, 
This config works great with SASS and CSS. Changes appears without reloading. 
After making any changes in JS file, page auto refresh just like in standard devServer mode and its working well too. 

But the problem occurs while changing .pug / .html files. 
With HMR enabled, saving any changes in pug file doesn't update the view in the browser (HRM and standard auto-refresh doesn't works) until you refresh website manually. 

Any ideas how this can be fixed? 

I found some solution based on including html files into js source file.. something like this:
```
if (process.env.NODE_ENV !== 'production') {
    require('file-loader!../index.html')
}
```

But if we have few different pages, then we have to include them all into main.js file - this can be quite annoying.

**Comment by Ihatetomatoes** [comment]
As the name of the repo suggest, this was only created to work with CSS.

For HTML and JS HMR you will need to follow the official guide:

https://webpack.js.org/concepts/hot-module-replacement/

Or wait until I create a tutorial on that.
